### ISSUE TITLE
System requirement for mobile devices

### ISSUE THREAD

**Issue by ocularbioengarhku** [Unity-Technologies/sentis-samples#10]
May I know is there anymore detail information about the system requirement for mobile devices?

I tried on the following devices:
Smooth effect - iphone 13 mini, Galaxy S23
Lag issue - iphone 6s, 7 plus, UleFone Armor 8 Pro, Nokia 7.2
Can’t run - Galaxy J7 Prime

So is there more concrete data to show what specification of mobile can work better or any minimum requirement?
Thank you!

**Comment by LiutaurasVy** [comment]
Hi, are you asking about any specific sample?

**Comment by ocularbioengarhku** [comment]
> Hi, are you asking about any specific sample?

Yes, I am now working on the [Depth Estimation](https://github.com/Unity-Technologies/sentis-samples/blob/main/DepthEstimationSample/README.md) sample

**Comment by AlexRibard** [comment]
Hey @ocularbioengarhku there is no concreet data on what specification to use.
This github is meant as a sample for users to play around with model temporal slicing.
For lower end phones, either lower the resolution or increase the inference time.
You can do this either by making ` inputTensor = TensorFloat.Zeros(new TensorShape(1, 3, 256, 256));` smaller
or `framesToExectute` bigger
