### ISSUE TITLE
Question on depth estimation model

### ISSUE THREAD

**Issue by rl27** [Unity-Technologies/sentis-samples#12]
Does the depth estimation model output relative depth or metric depth? I'm wondering if it can be used as a replacement for ARFoundation's Depth API.

**Comment by AlexRibard** [comment]
I'll link you the papers
https://pytorch.org/hub/intelisl_midas_v2/
https://arxiv.org/pdf/1907.01341v3.pdf
https://github.com/isl-org/MiDaS

It seems that it's the relative depth
