### ISSUE TITLE
MNIST example fails to recognize a lot of digits (any onnx mnist model) 

### ISSUE THREAD

**Issue by IgorAherne** [Unity-Technologies/sentis-samples#3]
Hello, 
the mnist example doesn't seem to classify the numbers for me, and I think the Softmax layer isn't working properly.
Appears to be a bug with the Sentis?

Can you please have a look:
https://discussions.unity.com/t/mnist-example-fails-to-recognize-a-lot-of-digits-any-onnx-mnist-model/315893

Thank you

**Comment by LiutaurasVy** [comment]
Responded in the Discussions thread. This can be closed

**Comment by LiutaurasVysniauskasUnity** [comment]
Responded in the Discussions thread linked above. This can be closed
