### ISSUE TITLE
Camera image is rotated 90 degrees in Unity Play mode and Mac app

### ISSUE THREAD

**Issue by patcat** [Unity-Technologies/sentis-samples#5]
When I run the DepthEstimationSample, the image from my webcam on my Macbooks comes through rotated 90 degrees (bottom of the webcam image instead displays on the left side of the screen).

The depth animation still runs from the bottom of the webcam image to the top, but is also rotated 90 degrees (from left side of the screen to the right).

So it seems the whole view is rotated 90 degrees — is this because I'm running it on a Mac rather than phone cam? Is there a simple fix for getting it to display correctly? I'm trying to make a desktop app with this sample, rather than a mobile one.

Thank you for your help!

**Comment by LiutaurasVysniauskasUnity** [comment]
This is known internally as Issue 339

**Comment by Aurimasp** [comment]
Hey @patcat , we have fixed the issue.
